spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9099

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mail:
  username:
  password: