spring:
  application:
    name: identity
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/