server:
  port: 9001

spring:
  application:
    name: authentication-service

jwt:
  secret: rbwHkHAn6y5cHul8gg+xZ3kLooA7AWWSeDLJtCc+ZeNEeVpJTl79/S6nbmygHQbzDdd4nSlsp09xLOx2qrtr9wmRhNMBNnGhkZzKbfT0XQ16y2YMdg7qBwya/778LBWD+e849FTo4QNmql7P0V5R9GCtJsaB0TTA+XlS41OkeKm5v66Ka/KXfR56W3UrGp0b/BS1g8R0+2t23g+hPXzvIs53opxYVQaDcYTElE1ooIQV3ocfoZR7SwhLCIbbFEUwPViHbC8PmGi2fvf4VB2GBx651HNKYNb5vNP90pOwqGrg+Oa6Qc4zchG8On6OpQYvH2T2xN5/zwfOb0m/wwj05Q==
  expiration: 86400
