spring:
  application:
    name: book
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/